### ISSUE TITLE
TypeError: 'str' object is not callable

### ISSUE THREAD

**Issue by njrl** [michaelfranzl/gerbil#1]
hallo,
schöne idee diese klasse, bloss leider wirft der reine aufruf (wie im beispiel) schon diesen fehler und mir ist nicht ganz klar warum.
getestet mit python3.5
```
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    grbl = Gerbil("my_grbl", "/dev/ttyUSB2")
  File "/home/xx/xx/gerbil/gerbil.py", line 355, in __init__
    self._callback("on_settings_downloaded", self.settings)
TypeError: 'str' object is not callable
```

**Comment by michaelfranzl** [comment]
Sorry, the README was out of date. I just updated the README.
